"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

interface CreateStreamerFormProps {
  onSubmit: (formData: FormData) => Promise<void>;
}

export default function CreateStreamerForm({ onSubmit }: CreateStreamerFormProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      const formData = new FormData(e.currentTarget);
      await onSubmit(formData);
      // Reset form on success
      (e.target as HTMLFormElement).reset();
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create streamer");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-6 mb-6">
      <h2 className="text-lg font-semibold mb-4">Add New Streamer</h2>
      
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Basic Info Section */}
        <div className="md:col-span-2">
          <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3 border-b pb-1">Basic Information</h3>
        </div>

        <div className="md:col-span-2">
          <label htmlFor="displayName" className="block text-sm font-medium text-gray-700 mb-1">
            Streamer Name *
          </label>
          <input
            type="text"
            id="displayName"
            name="displayName"
            required
            disabled={isSubmitting}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100"
            placeholder="e.g., Ninja, Shroud, xQc"
          />
        </div>
        
        {/* Hidden slug field - will be auto-generated by server action */}
        <input type="hidden" id="slug" name="slug" />

        <div>
          <label htmlFor="nsfw" className="block text-sm font-medium text-gray-700 mb-1">
            NSFW Content
          </label>
          <select
            id="nsfw"
            name="nsfw"
            disabled={isSubmitting}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100"
          >
            <option value="false">No</option>
            <option value="true">Yes</option>
          </select>
        </div>

        {/* Platform Links Section */}
        <div className="md:col-span-2 mt-4">
          <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3 border-b pb-1">Platform Channels</h3>
          <p className="text-sm text-gray-600 mb-4">Paste the full channel URL or just the username.</p>
        </div>

        <div className="md:col-span-2">
          <label htmlFor="twitchChannel" className="block text-sm font-medium text-gray-700 mb-1">
            Twitch Channel
          </label>
          <div className="flex">
            <span className="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
              twitch.tv/
            </span>
            <input
              type="text"
              id="twitchChannel"
              name="twitchChannel"
              disabled={isSubmitting}
              className="flex-1 min-w-0 block w-full px-3 py-2 rounded-none rounded-r-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100"
              placeholder="channelname"
            />
          </div>
        </div>

        <div className="md:col-span-2">
          <label htmlFor="youtubeChannel" className="block text-sm font-medium text-gray-700 mb-1">
            YouTube Channel
          </label>
          <div className="flex">
            <span className="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
              youtube.com/
            </span>
            <input
              type="text"
              id="youtubeChannel"
              name="youtubeChannel"
              disabled={isSubmitting}
              className="flex-1 min-w-0 block w-full px-3 py-2 rounded-none rounded-r-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100"
              placeholder="@channelname or channel/UC..."
            />
          </div>
        </div>

        <div className="md:col-span-2">
          <label htmlFor="kickChannel" className="block text-sm font-medium text-gray-700 mb-1">
            Kick Channel
          </label>
          <div className="flex">
            <span className="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
              kick.com/
            </span>
            <input
              type="text"
              id="kickChannel"
              name="kickChannel"
              disabled={isSubmitting}
              className="flex-1 min-w-0 block w-full px-3 py-2 rounded-none rounded-r-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100"
              placeholder="channelname"
            />
          </div>
        </div>
        
        <div className="md:col-span-2 mt-4">
          <label htmlFor="notes" className="block text-sm font-medium text-gray-700 mb-1">
            Notes
          </label>
          <textarea
            id="notes"
            name="notes"
            rows={3}
            disabled={isSubmitting}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100"
            placeholder="Additional notes about the streamer..."
          />
        </div>
        
        <div className="md:col-span-2 pt-4">
          <button
            type="submit"
            disabled={isSubmitting}
            className="w-full bg-blue-600 text-white py-2 px-6 rounded-md hover:bg-blue-700 transition-colors disabled:bg-blue-400 disabled:cursor-not-allowed font-medium"
          >
            {isSubmitting ? "Creating Streamer..." : "Add Streamer"}
          </button>
        </div>
      </form>
    </div>
  );
}